#!/bin/bash
#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.
#source $OPENSHIFT_GEAR_DIR/virtenv/bin/activate
cartridge_type="python-2.7"
source $OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/bin/activate
export PYTHON_EGG_CACHE=$OPENSHIFT_HOMEDIR/$cartridge_type/virtenv/lib/$cartridge_type

echo "Executing 'python $OPENSHIFT_REPO_DIR/manage.py syncdb --noinput"
python "$OPENSHIFT_REPODIR"manage.py syncdb --noinput
